name: Build on Windows
run-name: Build on Windows

on:
  merge_group:
    # We only build tsh and tctl on Windows so only consider Go code
    # (tsh and tctl don't run any Rust)
    paths:
      - '.github/workflows/build-windows.yaml'
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'build.assets/Makefile'
      - 'build.assets/Dockerfile*'
      - 'Makefile'

jobs:
  build:
    name: Build on Windows
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: windows-2022-16core

    permissions:
      contents: read

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v3

      - name: Get Go version
        id: go-version
        shell: bash
        run: echo "go-version=$(make --no-print-directory print-go-version | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version: ${{ steps.go-version.outputs.go-version }}

      - name: Build
        run: |
          $Env:OS="windows"
          make build/tsh
          make build/tctl
