name: Integration Tests (Root)
run-name: Integration Tests (Root) - ${{ github.run_id }} - @${{ github.actor }}

on:
  push:
    branches:
      - master
      - branch/*
  pull_request:
    paths:
      - '.github/workflows/integration-tests-root.yaml'
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'build.assets/Makefile'
      - 'build.assets/Dockerfile*'
      - 'Makefile'
  merge_group:
    paths:
      - '.github/workflows/integration-tests-root.yaml'
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'build.assets/Makefile'
      - 'build.assets/Dockerfile*'
      - 'Makefile'

jobs:
  test:
    name: Integration Tests (Root)
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-22.04-16core

    permissions:
      contents: read

    container:
      image: ghcr.io/gravitational/teleport-buildbox:teleport14
      options: --cap-add=SYS_ADMIN --privileged
      env:
        WEBASSETS_SKIP_BUILD: 1

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v3

      - name: Prepare workspace
        uses: ./.github/actions/prepare-workspace

      - name: Run tests
        timeout-minutes: 40
        run: |
          make integration-root RDPCLIENT_SKIP_BUILD=1
